import 'localized_survey.dart';
import 'survey_data.dart';

/// 日本市場向けの13問の題库。
///
/// パラメータの根拠:
///   - 月給基準：300,000 円（東京圏の正社員中央値相当）
///   - 労働時間：8時間理想、12時間で0点（日本の過労死ライン意識）
///   - 通勤：15分理想、90分で0点（首都圏は60分以上が多いため worst を90に）
///   - 賞与：5ヶ月で満点（夏冬合計で中堅以上の水準）
///   - 有休：20日で満点（法定最大20日に合わせる）
///   - WFH：3日で満点（ハイブリッド主流）
final surveyJa = LocalizedSurvey(
  questions: const <QuizQuestion>[
    NumericQuestion(
      id: 'workHours',
      category: '労働時間',
      title: '1日の実労働時間（残業含む）は？',
      hint: '直近1ヶ月の平均。0.5時間単位で入力できます。',
      baseline: 8,
      minValue: 4,
      maxValue: 16,
      defaultValue: 9,
      unit: '時間',
      quickPicks: [8, 9, 10, 11, 12],
      bestValue: 8,
      worstValue: 12,
      allowDecimal: true,
    ),
    NumericQuestion(
      id: 'commute',
      category: '通勤',
      title: '片道通勤時間は？',
      hint: '自宅からドア・トゥ・ドアの合計時間（乗換え含む）。',
      baseline: 45,
      minValue: 0,
      maxValue: 180,
      defaultValue: 45,
      unit: '分',
      quickPicks: [15, 30, 45, 60, 90],
      bestValue: 15,
      worstValue: 90,
    ),
    NumericQuestion(
      id: 'overtimeDays',
      category: '残業頻度',
      title: '直近1ヶ月、平均で週何日残業していますか？',
      hint: '定時を明らかに超えた日数。',
      baseline: 1,
      minValue: 0,
      maxValue: 7,
      defaultValue: 2,
      unit: '日/週',
      quickPicks: [0, 1, 2, 3, 5],
      bestValue: 0,
      worstValue: 4,
      allowDecimal: true,
    ),
    ChoiceQuestion(
      id: 'overtimePay',
      category: '残業手当',
      title: '残業手当はありますか？',
      hint: '割増賃金 / 代休の運用状況。',
      options: [
        QuizOption('残業なし', 'そもそも残業がないので不要。', 10),
        QuizOption('残業代が全額支給される', '1.25倍 / 1.35倍などで支給。', 9),
        QuizOption('代休のみ', '金銭ではないが休みで補填。', 6),
        QuizOption('みなし / サービス残業', 'いわゆるサビ残。', 0),
      ],
    ),
    ChoiceQuestion(
      id: 'restDays',
      category: '休日',
      title: '週末の休日状況は？',
      hint: '会社の実運用。',
      options: [
        QuizOption('完全週休2日制', '毎週2日休める。', 10),
        QuizOption('週休2日制（月に1-2回土曜出勤）', '隔週などで土曜出勤あり。', 6),
        QuizOption('週休1日', '日曜のみ休み。', 2),
        QuizOption('不定休 / シフト', 'シフト次第で呼び出しあり。', 0),
      ],
    ),
    NumericQuestion(
      id: 'lunchBreak',
      category: '昼休み',
      title: '昼休みに使える時間は？',
      hint: '食事 + 休憩。会社が実際に認めている長さ。',
      baseline: 60,
      minValue: 0,
      maxValue: 180,
      defaultValue: 60,
      unit: '分',
      quickPicks: [30, 45, 60, 75, 90],
      bestValue: 60,
      worstValue: 15,
    ),
    NumericQuestion(
      id: 'wfhDays',
      category: '在宅勤務',
      title: '週に何日リモート勤務できますか？',
      hint: '会社が認めている在宅 / リモートの日数。',
      baseline: 0,
      minValue: 0,
      maxValue: 5,
      defaultValue: 0,
      unit: '日/週',
      quickPicks: [0, 1, 2, 3, 5],
      bestValue: 3,
      worstValue: 0,
    ),
    NumericQuestion(
      id: 'annualBonus',
      category: '賞与',
      title: '年間賞与は月給の何ヶ月分ですか？',
      hint: '夏冬合計。なければ 0。',
      baseline: 2,
      minValue: 0,
      maxValue: 12,
      defaultValue: 2,
      unit: 'ヶ月',
      quickPicks: [0, 2, 4, 5, 6],
      bestValue: 5,
      worstValue: 0,
      allowDecimal: true,
    ),
    NumericQuestion(
      id: 'annualLeave',
      category: '有給休暇',
      title: '実際に消化できる年次有給休暇は？',
      hint: '名目ではなく、"実際に休める"日数。',
      baseline: 10,
      minValue: 0,
      maxValue: 30,
      defaultValue: 10,
      unit: '日',
      quickPicks: [5, 10, 15, 20, 25],
      bestValue: 20,
      worstValue: 5,
    ),
    RatingQuestion(
      id: 'environment',
      category: '職場環境',
      title: '職場環境の満足度は？',
      hint: 'デスク・機材・空調・全体の雰囲気など。',
      labels: ['非常に悪い', 'やや悪い', '普通', '良い', '非常に良い'],
    ),
    RatingQuestion(
      id: 'colleagues',
      category: '人間関係',
      title: '同僚・上司との関係は？',
      hint: '協力しやすさ、信頼感、サポート体制。',
      labels: ['非常に悪い', 'やや悪い', '普通', '良い', '非常に良い'],
    ),
    RatingQuestion(
      id: 'career',
      category: 'キャリア',
      title: 'キャリア成長 / 昇進の余地は？',
      hint: '学習機会・昇進ルート・昇給の実績。',
      labels: ['見込みなし', '少ない', '普通', '明確', '非常に良い'],
    ),
    NumericQuestion(
      id: 'salary',
      category: '月給',
      title: '税引前の月給（手取り前）は？',
      hint: '300,000 円 / 月を 1.0 係数とします（上限 ×2.5）。',
      baseline: 300000,
      minValue: 100000,
      maxValue: 2000000,
      defaultValue: 250000,
      unit: '円',
      quickPicks: [200000, 300000, 500000, 800000, 1000000],
      isSalaryMultiplier: true,
    ),
  ],
  improvementTips: const <String, String>{
    'workHours': '労基法の上限（月45時間）を意識。慢性的な超過は健康と生産性の両方を削ります。',
    'commute': '引っ越し / 近くの職場に転職 / リモート交渉 — 通勤30分減るだけで満足度は激変。',
    'overtimeDays': '恒常的な残業は人員不足か管理の問題。他社オファーと比較する価値あり。',
    'overtimePay': '割増賃金の未払いは労基法違反。証拠を残して労基に相談するか交渉を。',
    'restDays': '週1日未満の休みは違法。即座に転職シグナル。',
    'lunchBreak': '昼休みも満足に取れない会社は、集中力も健康も削られ続けます。',
    'wfhDays': 'フル出社は通勤コストと体力を増やします。最低でも週1-2日のリモート交渉を。',
    'annualBonus': '賞与が薄い場合は月給の昇給で補うよう交渉。業界相場と比較を。',
    'annualLeave': '有休を使い切れないなら"ない"のと同じ。実質的な残業として換算を。',
    'environment': '1日8時間いる場所の質は重要。HR に改善提案するか、異動 / 転職を検討。',
    'colleagues': '人間関係のコストは見えにくいが大きい。改善が無理なら部署異動を。',
    'career': '昇進の道筋が見えないなら、メンターや外部機会を能動的に探す。停滞は危険。',
    'salary': '同業同職の相場より大幅に低い場合、社内交渉、無理なら転職活動を。',
  },
  gradeDescriptions: const <String, String>{
    'S': '最高コスパ',
    'A': '良好',
    'B': 'まずまず',
    'C': 'やや物足りない',
    'D': '転職を検討する価値あり',
  },
  // ミーム称号 —— 2ちゃん / Twitter 風の自虐
  gradeMemeTitles: const <String, String>{
    'S': '勝ち組エース',
    'A': 'デキるサラリーマン',
    'B': '普通の会社員',
    'C': '疲弊サラリーマン',
    'D': '社畜最終形態',
  },
  gradeMemePunchlines: const <String, String>{
    'S': '社内で神扱い、同僚はあなたに憧れる存在。',
    'A': 'LinkedIn プロフィールが光る、「いいね」が止まらない。',
    'B': 'ごくごく平凡、可もなく不可もなく、ちょうどいい。',
    'C': '金曜の夜が唯一の光。月曜の朝は毎週地獄。',
    'D': '今すぐ転職準備を。心と体の SOS 信号です。',
  },
);
