import 'localized_survey.dart';
import 'survey_data.dart';

/// 中国大陆 locale 的 13 题题库。
///
/// 参数来源：一线 / 新一线城市打工人的常见中位数
///   - 月薪基准：10,000 元
///   - 工时容忍度：8 理想、13 零分（对应 12 小时强度）
///   - 通勤：10 理想、90 零分（跨区）
///   - 年终奖：6 个月满分（大厂年终奖水平）
///   - 年假：20 天满分（互联网公司福利）
final surveyZh = LocalizedSurvey(
  questions: const <QuizQuestion>[
    NumericQuestion(
      id: 'workHours',
      category: '工作时长',
      title: '每天实际工作时长（含加班）？',
      hint: '按最近一个月的平均状态填写，可精确到半小时。',
      baseline: 8,
      minValue: 4,
      maxValue: 16,
      defaultValue: 9,
      unit: '小时',
      quickPicks: [8, 9, 10, 11, 12],
      bestValue: 8,
      worstValue: 13,
      allowDecimal: true,
    ),
    NumericQuestion(
      id: 'commute',
      category: '通勤',
      title: '单程通勤时间？',
      hint: '门到门总时间（含等车 / 换乘），单位分钟。',
      baseline: 30,
      minValue: 0,
      maxValue: 180,
      defaultValue: 40,
      unit: '分钟',
      quickPicks: [15, 30, 45, 60, 90],
      bestValue: 10,
      worstValue: 90,
    ),
    NumericQuestion(
      id: 'overtimeDays',
      category: '加班频率',
      title: '最近一个月平均每周加班几天？',
      hint: '下班时间明显超出规定时间的天数。',
      baseline: 1,
      minValue: 0,
      maxValue: 7,
      defaultValue: 1,
      unit: '天/周',
      quickPicks: [0, 1, 2, 3, 5],
      bestValue: 0,
      worstValue: 5,
      allowDecimal: true,
    ),
    ChoiceQuestion(
      id: 'overtimePay',
      category: '加班补偿',
      title: '加班是否有补偿？',
      hint: '法定加班报酬 / 调休的落实情况。',
      options: [
        QuizOption('不需要加班', '基本不加班，用不上。', 10),
        QuizOption('有加班费（按 1.5 / 2 / 3 倍）', '按法律规定支付。', 9),
        QuizOption('可以调休', '不结算金额但能换假。', 6),
        QuizOption('白嫖 / 无任何补偿', '加班都是免费的。', 0),
      ],
    ),
    ChoiceQuestion(
      id: 'restDays',
      category: '休息日',
      title: '周末休息情况？',
      hint: '法定休息日的实际落实。',
      options: [
        QuizOption('双休', '每周完整 2 天休息。', 10),
        QuizOption('大小周', '每两周 3 天休。', 5),
        QuizOption('单休', '每周只休 1 天。', 2),
        QuizOption('无固定休息', '看排班 / 项目随时被叫走。', 0),
      ],
    ),
    NumericQuestion(
      id: 'lunchBreak',
      category: '午休',
      title: '午休可用时长？',
      hint: '含吃饭 + 休息，按公司实际允许的时长填。',
      baseline: 60,
      minValue: 0,
      maxValue: 180,
      defaultValue: 60,
      unit: '分钟',
      quickPicks: [30, 45, 60, 90, 120],
      bestValue: 90,
      worstValue: 15,
    ),
    NumericQuestion(
      id: 'wfhDays',
      category: '远程办公',
      title: '每周可远程办公天数？',
      hint: '公司允许的 WFH / 居家办公天数。',
      baseline: 0,
      minValue: 0,
      maxValue: 5,
      defaultValue: 0,
      unit: '天/周',
      quickPicks: [0, 1, 2, 3, 5],
      bestValue: 3,
      worstValue: 0,
    ),
    NumericQuestion(
      id: 'annualBonus',
      category: '年终奖',
      title: '年终奖约合几个月工资？',
      hint: '折算为基本月薪的月数。没有填 0，不确定按保守估计。',
      baseline: 1,
      minValue: 0,
      maxValue: 24,
      defaultValue: 1,
      unit: '个月',
      quickPicks: [0, 1, 2, 3, 6],
      bestValue: 6,
      worstValue: 0,
      allowDecimal: true,
    ),
    NumericQuestion(
      id: 'annualLeave',
      category: '年假',
      title: '实际可休的年假天数（法定 + 公司福利）？',
      hint: '不是名义上有的天数，是"真的能休完"的天数。',
      baseline: 5,
      minValue: 0,
      maxValue: 30,
      defaultValue: 5,
      unit: '天',
      quickPicks: [5, 10, 15, 20, 25],
      bestValue: 20,
      worstValue: 5,
    ),
    RatingQuestion(
      id: 'environment',
      category: '工作环境',
      title: '工作环境满意度？',
      hint: '硬件条件：工位、设备、办公氛围、通风空调等。',
      labels: ['很差', '不太好', '一般', '不错', '很好'],
    ),
    RatingQuestion(
      id: 'colleagues',
      category: '同事关系',
      title: '和同事 / 上下级的关系？',
      hint: '协作氛围、支持感、信任感。',
      labels: ['很差', '不太好', '一般', '不错', '很好'],
    ),
    RatingQuestion(
      id: 'career',
      category: '职业发展',
      title: '职业发展 / 晋升空间？',
      hint: '学习机会、晋升通道、薪资成长路径。',
      labels: ['无望', '很少', '一般', '清晰', '很好'],
    ),
    NumericQuestion(
      id: 'salary',
      category: '月薪',
      title: '你的税前月薪是多少？',
      hint: '以 10,000 元 / 月为 1.0 系数，越高得分越高（封顶 ×2.5）。',
      baseline: 10000,
      minValue: 1000,
      maxValue: 100000,
      defaultValue: 8000,
      unit: '元',
      quickPicks: [5000, 8000, 10000, 15000, 20000, 30000],
      isSalaryMultiplier: true,
    ),
  ],
  improvementTips: const <String, String>{
    'workHours': '评估工时是否合法，和管理沟通减负；长期超时工作代价远大于短期收益。',
    'commute': '搬家 / 就近换工作 / 争取远程，通勤每少 30 分钟，幸福感显著提升。',
    'overtimeDays': '加班频率高说明人力不足或管理问题，值得做跳槽对比。',
    'overtimePay': '无补偿加班违反《劳动法》，保留证据以备维权或谈判。',
    'restDays': '每周少于一天休息严重违规，是硬性跳槽信号。',
    'lunchBreak': '吃饭都赶时间的公司，健康和专注度都在被透支。',
    'wfhDays': '强制坐班会让通勤成本和体力消耗放大；争取至少每周 1-2 天远程。',
    'annualBonus': '年终奖少说明薪酬结构保守或公司业绩弱，谈薪时用月薪涨幅弥补。',
    'annualLeave': '年假没法真正休完，和"有年假"没区别；把它算进隐性加班。',
    'environment': '硬件条件影响每天 8 小时的基础体验，和 HR 提出改善或评估换岗。',
    'colleagues': '同事关系紧张是最隐性的成本，如果无法改善，考虑跨部门或换团队。',
    'career': '看不到上升通道时，主动找导师 / 外部机会；停留太久成长会停滞。',
    'salary': '薪资远低于市场同岗位时，优先尝试内部谈判，不行就看外部 offer。',
  },
  gradeDescriptions: const <String, String>{
    'S': '顶级性价比',
    'A': '不错',
    'B': '还行',
    'C': '勉强',
    'D': '建议考虑跳槽',
  },
);
